//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminServerManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonKnowledge
    {
        public byte[] CommonSkill { get; set; }
        public byte[] CommonProficiency { get; set; }
    }
}
