//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminServerManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T4DBEntities : DbContext
    {
        public T4DBEntities()
            : base("name=T4DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommonKnowledge> CommonKnowledges { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<TechnicalKnowledge> TechnicalKnowledges { get; set; }
    }
}
